#pragma once

// ReSharper disable once CppClassNeedsConstructorBecauseOfUninitializedMember
class engine_client_anarchy
{
public:
	AOLIB_OBJECT static PCSTR get_breed_str(breed_e breed_id);
	AOLIB_OBJECT character* get_client_char();
	AOLIB_OBJECT p_identity_t get_client_dynel_id(identity_t &id);
	AOLIB_OBJECT DWORD get_current_movement_mode();
	AOLIB_OBJECT n3_engine_client_anarchy_t get_engine_client_anarchy_data() const;
	AOLIB_OBJECT PCSTR get_faction_str(DWORD faction_id, bool full_name);
	AOLIB_OBJECT PCSTR get_faction_title(DWORD faction_id);
	AOLIB_OBJECT PCSTR get_gender_string(identity_t const &id);
	AOLIB_OBJECT p_dummy_item_base_t get_item_by_template(identity_t template_id, const identity_t &container_id);
	AOLIB_OBJECT static PCSTR get_sex_str(gender_e gender_id);
	AOLIB_OBJECT static PCSTR get_title_string(DWORD base, DWORD level);
	AOLIB_OBJECT bool is_first_login();
	AOLIB_OBJECT bool is_fixture(const identity_t &template_id, const identity_t &container_id);
	AOLIB_OBJECT void n3_msg_activate_mech(DWORD mech_id);
	AOLIB_OBJECT void n3_msg_airstrike(const identity_t &target_id);
	AOLIB_OBJECT void n3_msg_artillery_attack(const identity_t &target_id);
	AOLIB_OBJECT void n3_msg_assist_fight(const identity_t &assist_id);
	AOLIB_OBJECT bool n3_msg_can_attack(identity_t const &target_id);
	AOLIB_OBJECT bool n3_msg_can_click_target_target(const identity_t &identity_1, const identity_t &identity_2);
	AOLIB_OBJECT bool n3_msg_can_use_mech();
	AOLIB_OBJECT void n3_msg_cast_nano_spell(const identity_t &, const identity_t &);
	AOLIB_OBJECT DWORD n3_msg_consider(const identity_t &, float &);
	AOLIB_OBJECT void n3_msg_container_add_item(const identity_t &, const identity_t &);
	AOLIB_OBJECT void n3_msg_crawl_toggle();
	AOLIB_OBJECT void n3_msg_create_raid();
	AOLIB_OBJECT void n3_msg_default_action_on_dynel(const identity_t &);
	AOLIB_OBJECT void n3_msg_default_attack(const identity_t &, bool);
	AOLIB_OBJECT void n3_msg_delete_item(const identity_t &, const identity_t &);
	AOLIB_OBJECT void n3_msg_delete_nano(const identity_t &);
	AOLIB_OBJECT DWORD n3_msg_do_social_action(social_action_e);
	AOLIB_OBJECT void n3_msg_drop_item(const identity_t &, const vector3_t &);
	AOLIB_OBJECT void n3_msg_duel_accept();
	AOLIB_OBJECT void n3_msg_duel_challenge(const identity_t &);
	AOLIB_OBJECT void n3_msg_duel_draw();
	AOLIB_OBJECT void n3_msg_duel_refuse();
	AOLIB_OBJECT void n3_msg_duel_stop();
	AOLIB_OBJECT void n3_msg_forage();
	AOLIB_OBJECT DWORD n3_msg_get_action_by_name(PCSTR);
	AOLIB_OBJECT float n3_msg_get_action_progress(const identity_t &, DWORD*, DWORD*);
	AOLIB_OBJECT LONG n3_msg_get_agg_def();
	AOLIB_OBJECT PCSTR n3_msg_get_alien_level_string(const identity_t &);
	AOLIB_OBJECT void n3_msg_get_area_name(PCSTR*);
	AOLIB_OBJECT bool n3_msg_get_attacking_id(identity_t &);
	AOLIB_OBJECT PCSTR n3_msg_get_breed_str(const identity_t &);
	AOLIB_OBJECT DWORD n3_msg_get_buff_current_time(const identity_t &nano_id, const identity_t &character_id);
	AOLIB_OBJECT DWORD n3_msg_get_buff_total_time(const identity_t &, const identity_t &);
	AOLIB_OBJECT bool n3_msg_get_character_body_shape(BYTE &, identity_t);
	AOLIB_OBJECT bool n3_msg_get_char_orientation_data(const identity_t &, vector3_t &, quaternion_t &, float &);
	AOLIB_OBJECT PCSTR n3_msg_get_city_name_for_clan_member(const identity_t &);
	AOLIB_OBJECT PCSTR n3_msg_get_clan_level_string(const identity_t &);
	AOLIB_OBJECT string* n3_msg_get_clan_string(const identity_t &);
	AOLIB_OBJECT p_identity_t n3_msg_get_client_pet_id(identity_t &, DWORD);
	AOLIB_OBJECT bool n3_msg_get_close_target(identity_t &, bool, bool);
	AOLIB_OBJECT p_inventory_holder_t n3_msg_get_container_inventory_list(const identity_t &);
	AOLIB_OBJECT void n3_msg_get_correct_action_id(identity_t &);
	AOLIB_OBJECT LONG n3_msg_get_current_room();
	AOLIB_OBJECT PCSTR n3_msg_get_current_room_name();
	AOLIB_OBJECT DWORD n3_msg_get_district_fight_mode();
	AOLIB_OBJECT void n3_msg_get_dynels_in_vicinity(vector<identity_t>&, bool, bool, type_id_e);
	AOLIB_OBJECT bool n3_msg_get_faction_info_string(const identity_t &, string &);
	AOLIB_OBJECT bool n3_msg_get_faction_range(DWORD, DWORD &, DWORD &);
	AOLIB_OBJECT PCSTR n3_msg_get_first_name(const identity_t &);
	AOLIB_OBJECT double n3_msg_get_formula_progress(const identity_t &, DWORD &, DWORD &);
	AOLIB_OBJECT DWORD n3_msg_get_formula_radius(const identity_t &);
	AOLIB_OBJECT void n3_msg_get_global_character_position(vector3_t &);
	AOLIB_OBJECT void n3_msg_get_global_character_rotation(quaternion_t &);
	AOLIB_OBJECT PVOID n3_msg_get_grid_destination_list(const identity_t &);
	AOLIB_OBJECT PVOID n3_msg_get_grid_destination_list();
	AOLIB_OBJECT vector<p_inventory_data_t>* n3_msg_get_inventory_vec(const identity_t &);
	AOLIB_OBJECT void n3_msg_get_item(const identity_t &);
	AOLIB_OBJECT double n3_msg_get_item_progress(const identity_t &, DWORD &, DWORD &);
	AOLIB_OBJECT DWORD n3_msg_get_movement_mode();
	AOLIB_OBJECT PCSTR n3_msg_get_name(const identity_t &, const identity_t &);
	AOLIB_OBJECT DWORD n3_msg_get_nano_cost_modifier();
	AOLIB_OBJECT list<DWORD>* n3_msg_get_nano_spell_list();
	AOLIB_OBJECT list<nano_template_t>* n3_msg_get_nano_template_info_list(const identity_t &);
	AOLIB_OBJECT list<nano_template_t>* n3_msg_get_nano_template_info_list();
	AOLIB_OBJECT p_identity_t n3_msg_get_next_target(identity_t &, DWORD);
	AOLIB_OBJECT DWORD n3_msg_get_number_of_available_alien_perks();
	AOLIB_OBJECT DWORD n3_msg_get_number_of_available_perks();
	AOLIB_OBJECT DWORD n3_msg_get_number_of_free_inventory_slots();
	AOLIB_OBJECT DWORD n3_msg_get_number_of_used_alien_perks();
	AOLIB_OBJECT DWORD n3_msg_get_number_of_used_perks();
	AOLIB_OBJECT DWORD n3_msg_get_over_equip_level(const identity_t &);
	AOLIB_OBJECT PCSTR n3_msg_get_pf_name(DWORD);
	AOLIB_OBJECT PCSTR n3_msg_get_pf_name();
	AOLIB_OBJECT bool n3_msg_get_parent(const identity_t &, identity_t &);
	AOLIB_OBJECT bool n3_msg_get_pos(const identity_t &, vector3_t &);
	AOLIB_OBJECT LONG n3_msg_get_skill(DWORD, DWORD);
	AOLIB_OBJECT LONG n3_msg_get_skill(const identity_t &, DWORD, DWORD, const identity_t &);
	AOLIB_OBJECT LONG n3_msg_get_skill_max(DWORD);
	AOLIB_OBJECT list<special_action_t>* n3_msg_get_special_action_list();
	AOLIB_OBJECT DWORD n3_msg_get_special_action_state(const identity_t &);
	AOLIB_OBJECT PCSTR n3_msg_get_special_attack_weapon_name(const identity_t &);
	AOLIB_OBJECT static PVOID n3_msg_get_stat_name_map();
	AOLIB_OBJECT p_identity_t N3Msg_GetTargetTarget(identity_t &, const identity_t &);
	AOLIB_OBJECT PVOID N3Msg_GetTeamMemberList(LONG);
	AOLIB_OBJECT bool N3Msg_HasPerk(DWORD);
	AOLIB_OBJECT bool N3Msg_IsAttacking() const;
	AOLIB_OBJECT bool N3Msg_IsBattleStation();
	AOLIB_OBJECT bool N3Msg_IsCharacterInMech(identity_t);
	AOLIB_OBJECT bool N3Msg_IsCharacterMorphed(identity_t);
	AOLIB_OBJECT bool N3Msg_IsDungeon();
	AOLIB_OBJECT bool N3Msg_IsFormulaReady(const identity_t &);
	AOLIB_OBJECT bool N3Msg_IsGeneralPerk(DWORD);
	AOLIB_OBJECT bool N3Msg_IsGroupPerk(DWORD);
	AOLIB_OBJECT bool N3Msg_IsInRaidTeam();
	AOLIB_OBJECT bool N3Msg_IsInTeam(const identity_t &);
	AOLIB_OBJECT bool N3Msg_IsItemDisabled(const identity_t &, const identity_t &);
	AOLIB_OBJECT bool N3Msg_IsItemMine(const identity_t &);
	AOLIB_OBJECT bool N3Msg_IsItemNFCrystal(const identity_t &, const identity_t &);
	AOLIB_OBJECT bool N3Msg_IsItemPossibleToUnWear(const identity_t &);
	AOLIB_OBJECT bool N3Msg_IsItemPossibleToWear(const identity_t &, DWORD, DWORD, bool, DWORD);
	AOLIB_OBJECT bool N3Msg_IsMoving();
	AOLIB_OBJECT bool N3Msg_IsMyPetID(const identity_t &);
	AOLIB_OBJECT bool N3Msg_IsNanoSelfOnly(const identity_t &);
	AOLIB_OBJECT bool n3_msg_is_npc(const identity_t &);
	AOLIB_OBJECT bool N3Msg_IsPerk(DWORD);
	AOLIB_OBJECT bool N3Msg_IsPetTower(const identity_t &);
	AOLIB_OBJECT bool N3Msg_IsProfessionPerk(DWORD);
	AOLIB_OBJECT bool N3Msg_IsResearch(DWORD);
	AOLIB_OBJECT bool N3Msg_IsSecondarySpecialAttackAvailable(DWORD);
	AOLIB_OBJECT bool N3Msg_IsShieldDisablerItem(const identity_t &);
	AOLIB_OBJECT bool N3Msg_IsSpecialPerk(DWORD);
	AOLIB_OBJECT bool N3Msg_IsTeamLeader(const identity_t &);
	AOLIB_OBJECT bool N3Msg_IsTeamMission(const identity_t &);
	AOLIB_OBJECT bool N3Msg_IsTeamMissionCopy(const identity_t &);
	AOLIB_OBJECT bool N3Msg_IsTeamNano(const identity_t &);
	AOLIB_OBJECT bool N3Msg_IsTower(const identity_t &);
	AOLIB_OBJECT bool N3Msg_IsVisible(const identity_t &);
	AOLIB_OBJECT bool N3Msg_JoinItems(const identity_t &, const identity_t &);
	AOLIB_OBJECT void N3Msg_KickTeamMember(const identity_t &);
	AOLIB_OBJECT void N3Msg_LeaveBattle();
	AOLIB_OBJECT void N3Msg_LeaveTeam();
	AOLIB_OBJECT bool N3Msg_MeetsPerkCriteria(DWORD);
	AOLIB_OBJECT bool N3Msg_MoveItemToInventory(const identity_t &, DWORD, DWORD);
	AOLIB_OBJECT void N3Msg_MoveRaidMember(const identity_t &, DWORD);
	AOLIB_OBJECT bool N3Msg_NameToID(const std::string &, identity_t &);
	AOLIB_OBJECT void N3Msg_NPCChatAddTradeItem(const identity_t &, const identity_t &, const identity_t &);
	AOLIB_OBJECT void N3Msg_NPCChatCloseWindow(const identity_t &, const identity_t &);
	AOLIB_OBJECT void N3Msg_NPCChatEndTrade(const identity_t &, const identity_t &, DWORD, bool);
	AOLIB_OBJECT void N3Msg_NPCChatRemoveTradeItem(const identity_t &, const identity_t &, const identity_t &);
	AOLIB_OBJECT void N3Msg_NPCChatRequestDescription(const identity_t &, const identity_t &);
	AOLIB_OBJECT void N3Msg_NPCChatStartTrade(const identity_t &, const identity_t &);
	AOLIB_OBJECT void N3Msg_OrbitalAttack(const identity_t &);
	AOLIB_OBJECT bool N3Msg_PerformSpecialAction(DWORD);
	AOLIB_OBJECT bool N3Msg_PerformSpecialAction(const identity_t &);
	AOLIB_OBJECT void N3Msg_PetDuel_Accept();
	AOLIB_OBJECT void N3Msg_PetDuel_Challenge(const identity_t &);
	AOLIB_OBJECT void N3Msg_PetDuel_Refuse();
	AOLIB_OBJECT void N3Msg_PetDuel_Stop();
	AOLIB_OBJECT bool N3Msg_RemoveBuff(const identity_t &);
	AOLIB_OBJECT void N3Msg_RemoveQuest(const identity_t &);
	AOLIB_OBJECT std::list<inventory_entry_t>* N3Msg_RequestCharacterInventory();
	AOLIB_OBJECT std::list<inventory_entry_t>* N3Msg_RequestClothInventory(const identity_t &);
	AOLIB_OBJECT std::list<inventory_entry_t>* N3Msg_RequestImplantInventory(const identity_t &);
	AOLIB_OBJECT std::list<inventory_entry_t>* N3Msg_RequestSocialInventory(const identity_t &);
	AOLIB_OBJECT std::list<inventory_entry_t>* N3Msg_RequestWeaponInventory(const identity_t &);
	AOLIB_OBJECT bool N3Msg_SecondarySpecialAttack(const identity_t &, DWORD);
	AOLIB_OBJECT void N3Msg_SelectedTarget(const identity_t&);
	AOLIB_OBJECT void N3Msg_SendPetCommand(DWORD, const identity_t &, DWORD, DWORD, PCSTR); // 0, PetIdentity&, PetCommand_e, 0, nullptr
	AOLIB_OBJECT void N3Msg_SitToggle();
	AOLIB_OBJECT bool N3Msg_SplitItem(const identity_t &, DWORD);
	AOLIB_OBJECT void N3Msg_StartAltState();
	AOLIB_OBJECT bool N3Msg_StartCamping();
	AOLIB_OBJECT void N3Msg_StartPvP(const identity_t &);
	AOLIB_OBJECT bool N3Msg_StartTreatment(const identity_t &);
	AOLIB_OBJECT void N3Msg_StopAltState();
	AOLIB_OBJECT void N3Msg_StopAttack();
	AOLIB_OBJECT void N3Msg_StopCamping();
	AOLIB_OBJECT DWORD N3Msg_StringToStat(PCSTR);
	AOLIB_OBJECT void N3Msg_SwitchTarget(const identity_t &);
	AOLIB_OBJECT bool N3Msg_TeamJoinRequest(const identity_t &, bool);
	AOLIB_OBJECT p_identity_t N3Msg_TemplateIDToDynelID(identity_t &, const identity_t &); // dummy, template
	AOLIB_OBJECT bool N3Msg_TextCommand(DWORD, PCSTR, const identity_t &);
	AOLIB_OBJECT void N3Msg_ToggleReclaim(bool);
	AOLIB_OBJECT void N3Msg_TradeAbort(bool);
	AOLIB_OBJECT void N3Msg_TradeAccept();
	AOLIB_OBJECT void N3Msg_TradeAddItem(const identity_t &, const identity_t &, DWORD);
	AOLIB_OBJECT void N3Msg_TradeConfirm();
	AOLIB_OBJECT PVOID N3Msg_TradeGetInventory(const identity_t &);
	AOLIB_OBJECT DWORD N3Msg_TradeGetInventoryCost(const identity_t &);
	AOLIB_OBJECT void N3Msg_TradeRemoveItem(const identity_t &, const identity_t &);
	AOLIB_OBJECT void N3Msg_TradeSetCash(DWORD);
	AOLIB_OBJECT void N3Msg_TradeStart(const identity_t &);
	AOLIB_OBJECT void N3Msg_TradeskillCombine(const identity_t &, const identity_t &);
	AOLIB_OBJECT bool N3Msg_TrainPerk(DWORD);
	AOLIB_OBJECT void N3Msg_TransferTeamLeadership(const identity_t &);
	AOLIB_OBJECT void N3Msg_TryAbortNanoFormula();
	AOLIB_OBJECT void N3Msg_TryEnterSneakMode();
	AOLIB_OBJECT bool N3Msg_UntrainPerk(DWORD);
	AOLIB_OBJECT void N3Msg_UseItem(const identity_t &, bool);
	AOLIB_OBJECT void N3Msg_UseItemOnItem(const identity_t &, const identity_t &);	


	private:
	// ReSharper disable once CppUninitializedNonStaticDataMember
	n3_engine_client_anarchy_t n3_engine_client_anarchy_;






};
